get url form DOCKER_COMPOSE_DOWNLOAD_LINK if exist
tinkerbell/tink pull request #305
Opened 2020-09-23 12:21 UTC by MaxPeal

## Description

get url form DOCKER_COMPOSE_DOWNLOAD_LINK if exist

## Why is this needed

to doit on the same way like the setup.sh

Fixes: #

## How Has This Been Tested?
just testit it localy

## How are existing users impacted? What migration steps/scripts do we need?

no migration steps needed

2020-09-24 07:00 UTC, gianarb commented
Hello! Thank you @MaxPeal for your contribution! And welcome!!

A few things:

1. Do you mind explaining why you are introducing a new option in the `setup.sh`? You can write it `Why is this needed` the current section does not really explain to me why you need that variable.
2. Do you mind to squash your commits in a single one?
3. We use (shellcheck)[https://www.shellcheck.net/] to statically analyze bash scrits. Your changes are currently not complaint. Do you mind to fix them?

2020-09-24 07:00 UTC, gianarb requested changes
Hello! Thank you @MaxPeal for your contribution! And welcome!!

A few things:

1. Do you mind explaining why you are introducing a new option in the `setup.sh`? You can write it `Why is this needed` the current section does not really explain to me why you need that variable.
2. Do you mind to squash your commits in a single one?
3. We use (shellcheck)[https://www.shellcheck.net/] to statically analyze bash scrits. Your changes are currently not complaint. Do you mind to fix them?

2021-07-27 16:52 UTC, tstromberg commented on deploy/vagrant/scripts/tinkerbell.sh
> +	local lsb_dist
This work to support other LSB distributions should be moved to a separate PR.

2021-08-10 19:45 UTC, displague commented
Fixes https://github.com/tinkerbell/tink/issues/518

2021-08-10 20:06 UTC, displague commented
I've opened a new rebased, conflict merged, PR with some of the changes from this PR, @MaxPeal.

See https://github.com/tinkerbell/tink/pull/519

Any vagrant work will need to be moved to tinkerbell/sandbox.  I created an issue to track that #518, but closed it when I realized that vagrant was removed from this repo.

Closing this PR in favor of #519.

2021-08-10 20:06 UTC, closed without merging