Document all the grpc api and generate html documentation
tinkerbell/tink pull request #375
Opened 2020-12-04 12:38 UTC by gianarb

## Description

Document the grpc api and generate an HTML page that can be deployed somewhere

- [x] bootstrap doc
- [x] find a way to generate an HTML version of it
- [ ] CI/CD for the API somehow somewhere. Probably not here. probably starting from sandbox as part of the release workflow. Not sure yet. I am open to feedback and help here, I am tired to do GitHub action all day.
- [ ] I would like to have @mmlb and @kdeng3849 having a look, maybe deprecating fields and methods we don't want (please just push a commit or open a pr against this one)
- [ ] everybody @thebsdbox , @mmlb , @nathangoulding @kdeng3849 please please please, send PR against this one with more documentation, some of the fields and methods need love.

## Why is this needed

Documentation is important.

Fixes: #219 probably many more

## How Has This Been Tested?

`make grpc/gen_doc` and looking at the generated HTML page in `doc` folder

2020-12-09 18:35 UTC, thebsdbox requested changes
There are a few things that I noticed, but I think this is a great start to having documentation around the API.

2020-12-09 18:35 UTC, thebsdbox commented on protos/hardware/hardware.proto
> + * It can be identifed with its own UUID but more in general it can be everything that has a Mac address.
~everything~ anything that has a ~Mac~ MAC address.

2020-12-09 18:35 UTC, thebsdbox commented on protos/hardware/hardware.proto
> + * an hardware.
~an~ a piece of hardware

2020-12-09 18:35 UTC, thebsdbox commented on protos/hardware/hardware.proto
> +   * hardware describes how the hardware you want to register to Tinkerbell looks like.
~h~Hardware describes ~how~ the hardware ..

2020-12-09 18:35 UTC, thebsdbox commented on protos/hardware/hardware.proto
> +   * hardware describes how the hardware you want to register to Tinkerbell looks like.
to Tinkerbell "and what it" looks like.

2020-12-09 18:35 UTC, thebsdbox commented on protos/hardware/hardware.proto
> +   * Hostname, mac address, DHCP, network interfaces, metadata and so on.
~mac~MAC

2020-12-09 18:35 UTC, thebsdbox commented on protos/hardware/hardware.proto
> +     * Configure the network interfaces you have in your hardware and how their
and ~how~ defines their

2020-12-09 18:35 UTC, thebsdbox commented on protos/workflow/workflow.proto
> + * WorkflowSerive exposese various capabilities when it comes to starting and
~WorkflowSerive~ WorkflowService ~exposeses~ exposes

2020-12-09 18:35 UTC, thebsdbox commented on protos/workflow/workflow.proto
> +   * template. From now one the selected hardware is capable of picking the
From now on~e~ the selected hardware

2020-12-09 22:40 UTC, kdeng3849 submitted a review, later dismissed

2020-12-09 22:40 UTC, kdeng3849 commented on protos/hardware/hardware.proto
> +    reserved 2;
can we keep the `// obsolete` tombstones just so we have a clear record of what was deprecated / reason why the number is reserved?

2020-12-09 22:40 UTC, kdeng3849 commented on protos/workflow/workflow.proto
> +   * On failure used to be a way to execute an action if the current one timesout
`timesout` should be `times out`

2021-01-29 11:43 UTC, thebsdbox approved these changes

2021-02-01 21:00 UTC, mmlb approved these changes

2021-02-01 21:21 UTC, merged