Fix #377: Removing `name` flag from the 'tink template create/update' command
tinkerbell/tink pull request #385
Opened 2020-12-11 08:59 UTC by parauliya

Signed-off-by: parauliya <aman@infracloud.io>

## Description

This PR will remove the `name` flag from the `tink template create/update` command in tink-cli.

## Why is this needed

Fixes: #377 

## How Has This Been Tested?
This has been tested manually through vagrant setup and in the tink-cli container only.

## How are existing users impacted? What migration steps/scripts do we need?
Existing users needs to run the `tink template update <Id> -p <existing template>` command. This will update the name of each template as per the value of `name` field inside the template itself.

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [x] provided instructions on how to upgrade

2020-12-11 09:45 UTC, gianarb commented
This is a BC break and I think we should take this opportunity to carefully review our UX.

This is what I mean in practice: `tink hardware push` uses `-f` to require the location for a file, here we use `-p` for the same thing. Should we move it to `-f` in gain some sort consistency?

2020-12-11 10:12 UTC, gauravgahlot commented
> This is a BC break and I think we should take this opportunity to carefully review our UX.
> 
> This is what I mean in practice: `tink hardware push` uses `-f` to require the location for a file, here we use `-p` for the same thing. Should we move it to `-f` to gain some sort of consistency?

`tink hardware push` does not have a shorthand for file path and uses `--file`. `-f` is used for the facility. 
```
Usage:
  tink hardware push [flags]

Examples:
cat /tmp/data.json | tink hardware push
tink hardware push --file /tmp/data.json

Flags:
      --file string   hardware data file
  -h, --help          help for push

Global Flags:
  -f, --facility string   used to build grpc and http urls

either pipe the data or provide the required '--file' flag
```

That's the reason why we had to use `-p` for the file path.

2020-12-11 10:14 UTC, gianarb commented
Thank you for clarifying @gauravgahlot but my point is the same:

hardware use `--file` when asking for the location for a file.
template uses `-p` for the same reason.

Should we use the same one? 👍 👎

2020-12-11 10:18 UTC, gauravgahlot commented
> Thank you for clarifying @gauravgahlot but my point is the same:
> 
> hardware use `--file` when asking for the location for a file.
> template uses `-p` for the same reason.
> 
> Should we use the same one?

Oh yes totally. Initially, we had thought of removing `facility` altogether and use `-f` for the file path. But I'm assuming the facility is required in the Packet environment. 🤔

2020-12-11 10:20 UTC, gianarb commented
> But I'm assuming the facility is required in the Packet environment

Never say to me that something is required for ONE single company.. :) but yeah for now I think we should use `--file` and leave the facility, probably when @mmlb will start removing Packet or dead code from all the repo `-f/--facility` will go away, but out of scope for now.

2020-12-11 10:36 UTC, gauravgahlot requested changes

2020-12-11 10:36 UTC, gauravgahlot commented on cmd/tink-cli/cmd/template/create.go
> +type TemplateName struct {
Should not be an exported type.

2020-12-11 10:36 UTC, gauravgahlot commented on cmd/tink-cli/cmd/template/create.go
> +cat /tmp/example.tmpl | tink template create `,
Can we please add more examples in the `Long` description?
For reference, you can check [`tink events watch`](https://github.com/tinkerbell/tink/blob/master/cmd/tink-cli/cmd/events/watch.go#L70).

2020-12-11 10:36 UTC, gauravgahlot commented on cmd/tink-cli/cmd/template/create.go
> +	return errors.New("Template does not have `name` field which is mandatory")
Please move all the error messages to a `const` and ensure they all start with a lower case.

2020-12-11 15:20 UTC, mmlb commented
> > But I'm assuming the facility is required in the Packet environment
> 
> Never say to me that something is required for ONE single company.. :) but yeah for now I think we should use `--file` and leave the facility, probably when @mmlb will start removing Packet or dead code from all the repo `-f/--facility` will go away, but out of scope for now.

Facility is only really used for the cert generation stuff, something I'd actually like to get rid of. Let me open up an issue for that (#389).

2020-12-11 21:45 UTC, gianarb requested changes
Great, @parauliya do you mind changing `-p` with `--file` and we are good? Thanks

2020-12-14 18:04 UTC, mmlb approved these changes

2020-12-14 18:08 UTC, mmlb requested changes

2020-12-14 18:08 UTC, mmlb commented on cmd/tink-cli/cmd/template/create.go
> +	return errors.New("Template does not have `name` field which is mandatory")
This should use `github.com/tinkerbell/tink/workflow.Parse` instead.

2020-12-15 09:07 UTC, gianarb requested changes
This is a bc break, according with the proposal 0011 https://github.com/tinkerbell/proposals/blob/master/proposals/0011/README.md can you add a chapter in the PR description:

# How to migrate

https://github.com/tinkerbell/proposals/blob/master/proposals/0011/README.md#how-to-migrate

Explaining what is not working anymore and how to do the same in the new way, thanks

2020-12-15 09:07 UTC, gianarb commented on cmd/tink-cli/cmd/template/create.go
>  	flags.StringVarP(&filePath, "path", "p", "", "path to the template file")
Please change this with `--file` to unify with `hardware push`

2020-12-23 12:20 UTC, gauravgahlot submitted a review, later dismissed

2020-12-23 22:45 UTC, gianarb requested changes

2020-12-23 22:45 UTC, gianarb commented on cmd/tink-cli/cmd/template/create.go
> +				return errors.New("either pipe the template or provide the required '--path' flag")
I think this is `'--file' flag` now

2020-12-24 10:19 UTC, gianarb approved these changes

2020-12-29 05:22 UTC, gauravgahlot commented
No code changes only updated the branch.

2020-12-29 08:24 UTC, gianarb approved these changes

2021-01-04 07:00 UTC, gauravgahlot approved these changes

2021-01-04 08:25 UTC, gianarb approved these changes

2021-01-04 17:01 UTC, gauravgahlot commented
@mmlb Please let me know once you are back, and I will update the branch (one last time). 😄

2021-01-04 20:31 UTC, mmlb requested changes

2021-01-04 20:31 UTC, mmlb commented on cmd/tink-cli/cmd/template/create.go
> +	filePath string
I don't quite see the reason for `file` global var when its not used in the `flags.StringVarP` call. It should either be named a little more descriptively (filePathArgName?) and used there too or we just hard code use of `"file"` every where.

I'm not a fan of the "variable for the variable name" approach...

2021-01-04 20:31 UTC, mmlb commented on cmd/tink-cli/cmd/template/create.go
> +			path, _ := c.Flags().GetString(file)
path isn't ever being used right?

2021-01-04 20:31 UTC, mmlb commented on cmd/tink-cli/cmd/template_test.go
> +				if !strings.Contains(out.String(), "Create template using the --file flag") {
can be DRY'd by doing:
```go
want := "Create template using the --file flag"
if !strings.Contains(out.String(), want) {
    t.Error("unexpected output, looking for %q as a substring in %q", want, out.String())
}
```
or similar

2021-01-04 20:31 UTC, mmlb commented on cmd/tink-cli/cmd/template_test.go
> +				if !strings.Contains(out.String(), "Update an existing template") {
ditto

2021-01-12 09:14 UTC, gauravgahlot submitted a review, later dismissed

2021-01-21 09:30 UTC, gianarb approved these changes

2021-01-21 09:31 UTC, gauravgahlot approved these changes

2021-01-21 15:35 UTC, mmlb approved these changes

2021-01-21 15:36 UTC, merged