while setting up provisioner, check if osie file path is valid
tinkerbell/tink pull request #411
Opened 2021-01-04 13:21 UTC by Cbkhare

## Description
While creating provisioner, if `TB_OSIE_TAR` is set then osie file is extracted from the file whose location/absolute path is the value of this variable. 

## Why is this needed

if `TB_OSIE_TAR` is set and the file is not present at the given path(value of TB_OSIE_TAR) workflow fails stating the Linux image is not found. Which is valid as osie directory under `deploy/state` would be empty. 

Fixes: #
- check has been added to verify if the file is present in the given path or not. 
- 
## How Has This Been Tested?
By creating the provisioner.
Provisioner is not created if a tar file is present at the location defined in `TB_OSIE_TAR`. 

**on success** 
![Screenshot from 2021-01-04 18-50-51](https://user-images.githubusercontent.com/13061957/103539342-df798280-4ebd-11eb-81c5-e559fe1a152d.png)

**On failure** 
![Screenshot from 2021-01-04 18-48-44](https://user-images.githubusercontent.com/13061957/103539136-86115380-4ebd-11eb-9e97-b1abe35ab986.png)

2021-01-06 15:04 UTC, mmlb commented
Shouldn't this already be caught by `tar` exiting with an error and `set-e` being set?

2021-01-12 02:55 UTC, Cbkhare commented
> Shouldn't this already be caught by `tar` exiting with an error and `set-e` being set?

@mmlb , right, I think the script is not bailing out in that case. With this PR it goes for a graceful exit.

2021-06-29 15:33 UTC, tstromberg requested changes

2021-06-29 15:33 UTC, tstromberg commented on setup.sh
> +				echo "$INFO extracting osie tar"
Please remove the "else" and move this echo statement to appear just before the `tar`. This will make the code easier to follow.

2021-07-27 15:34 UTC, tstromberg commented
This PR looks great! The DCO checker noticed that one of your git commits isn't signed properly - can you fix that so that this PR may be merged?

https://github.com/tinkerbell/tink/pull/411/checks?check_run_id=2999422937 has instructions on how to fix this PR.

2021-07-27 17:50 UTC, gauravgahlot commented
@tstromberg I tried those steps already but didn't work. Will it be okay if I close this PR and create a new one. I know the original contributor personally and I don't think he is looking into Tinkerbell anymore.

2021-08-24 15:23 UTC, nshalman commented
> @tstromberg I tried those steps already but didn't work. Will it be okay if I close this PR and create a new one?
> I know the original contributor personally and I don't think he is looking into Tinkerbell anymore.

@gauravgahlot That would be great. I'll close out this one.

2021-08-24 15:23 UTC, closed without merging