fix some errors under bugsmash ineffectual assignment
tinkerbell/tink pull request #498
Opened 2021-05-07 13:23 UTC by soniasingla

2021-05-07 14:27 UTC, markyjackson-taulia requested changes
Also would like to understand why the changes in the file permissions

2021-05-21 19:06 UTC, soniasingla commented on cmd/tink-worker/internal/worker.go
> -	f, err := os.OpenFile(wfDir+string(os.PathSeparator)+dataFile, os.O_RDWR|os.O_CREATE, 0644)
@parauliya musedev bot is saying it needs to be changed

2021-05-21 21:58 UTC, soniasingla commented on cmd/tink-worker/internal/worker.go
> -	f, err := os.OpenFile(wfDir+string(os.PathSeparator)+dataFile, os.O_RDWR|os.O_CREATE, 0644)
because of gosec error

2021-05-22 07:07 UTC, soniasingla commented
> Also would like to understand why the changes in the file permissions

musedev bot is saying it needs to be changed because of gosec error under  golint

2021-06-02 12:17 UTC, gauravgahlot commented
> > Also would like to understand why the changes in the file permissions
> 
> musedev bot is saying it needs to be changed because of gosec error under golint

How did you test the changes?

2021-06-02 12:18 UTC, gauravgahlot commented
@soniasingla How did you test these changes?

2021-06-29 15:41 UTC, Raj-Dharwadkar commented
@soniasingla Please can you rebase and address the comments ?

2021-06-29 17:09 UTC, soniasingla commented
@Raj-Dharwadkar closing this PR since the golint errors are not valid, thanks for checking :)

2021-06-29 17:09 UTC, closed without merging