Add functionality for users to retrieve template by Name as well as UUID
tinkerbell/tink pull request #523
Opened 2021-08-25 01:39 UTC by Belchy06

Signed-off-by: William Belcher <william.belcher@hotmail.com>

## Description

This PR adds the ability for Tink to retrieve workflows by either UUID or by Name. If the value after `tink template get` is not a valid UUID, Tink will default to searching for the value in the Name field of the templates. 

This PR also adds a TemplateClient to the TInk client, allowing other services such as Boots to retrieve templates.

## Why is this needed

This feature is required for the project I am working on but I am sure there are many other use cases I'm unaware of. Also, https://github.com/tinkerbell/boots/issues/178

## How Has This Been Tested?
This has been tested in the VM's based on the [Local Setup with Vagrant](https://docs.tinkerbell.org/setup/local-vagrant/) tutorial.

## How are existing users impacted? What migration steps/scripts do we need?

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

2021-08-25 01:41 UTC, Belchy06 commented
@tstromberg I had done something funky with my last PR for this and was unable to get the DCO signed off correctly.

This PR is essentially the same as the last, just compressed into a single commit with DCO signed off.

2021-08-25 15:08 UTC, mmlb requested changes

2021-08-25 15:08 UTC, mmlb commented on client/main.go
> +}
Lets get rid of this from this PR please. boots does not need template access so lets wait until an actual need comes up for this.

2021-08-25 15:08 UTC, mmlb commented on protos/template/template.pb.go
> +	sync "sync"
please drop this change.

2021-09-01 23:58 UTC, Belchy06 commented
Sorry I haven't gotten around to those changes yet @tstromberg , I've been super busy. Will get around to them this weekend.

2021-09-10 17:02 UTC, tstromberg commented
@Belchy06 - hey, just checking in to see if there is anything you would like help with here. I'm eager to see this PR be merged so that folks can use it :)

2021-09-13 01:26 UTC, closed without merging